<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UserTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    protected function tearDown(): void
    {
        //pendiente: borrar usuario.
    }
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_example()
    {
        $response = $this->post('/login',[
            'email'=>'correo@correo.com',
            'password'=>'abc123',
            'boton'=>'Login',
            '_token'=>'eC5FYCUmqkkeb6nhLmbd396njQzTviye1Mvi0xaY']);
        $response->assertStatus(302);
        //$contenido=$response->getContent();
        //var_dump($response->headers);

        $response->assertHeader('razon','ok');


    }
    public function test_example2()
    {
        $response = $this->post('/login',[
            'email'=>'correo@correo.com',
            'password'=>'abc123xxx',
            'boton'=>'Login',
            '_token'=>'eC5FYCUmqkkeb6nhLmbd396njQzTviye1Mvi0xaY']);
        $response->assertStatus(302);
        $response->assertHeader('razon','fallo');



    }
}
